/* eslint-disable import/no-anonymous-default-export */

export default {
  SHOW_PREVIOUS_QUESTION: "SHOW_PREVIOUS_QUESTION",
  ALLOW_USER_REPEAT_BALANCE_QUESTION: "ALLOW_USER_REPEAT_BALANCE_QUESTION",
  CONSISTENCY_RATIO_MATRIX: "CONSISTENCY_RATIO_MATRIX",
  CORRELATION_LIMIT_VALUE: "CORRELATION_LIMIT_VALUE",
  SHOW_RESULTS_AFTER: "SHOW_RESULTS_AFTER",
  SHOW_RESULTS_BEFORE: "SHOW_RESULTS_BEFORE",
  PROLIFIC_COMPLETION_URL: "PROLIFIC_COMPLETION_URL",
  ANONYMOUS_SESSION_MAX_TIME: "ANONYMOUS_SESSION_MAX_TIME",
  ANONYMOUS_SESSION_SHOW_ALERT_TIME: "ANONYMOUS_SESSION_SHOW_ALERT_TIME",
  SHOW_RESTART_QUESTIONS_BUTTON: "SHOW_RESTART_QUESTIONS_BUTTON",
};
