/* eslint-disable import/no-anonymous-default-export */

export default {
  SHOW_PREVIOUS_QUESTION: "SHOW_PREVIOUS_QUESTION",
  ALLOW_USER_REPEAT_BALANCE_QUESTION: "ALLOW_USER_REPEAT_BALANCE_QUESTION",
  CONSISTENCY_RATIO_MATRIX: "CONSISTENCY_RATIO_MATRIX",
  CORRELATION_LIMIT_VALUE: "CORRELATION_LIMIT_VALUE",
};
