export const QUESTION_ACTIVE = "ACTIVE";
export const QUESTION_NOT_ACTIVE = "NOT_ACTIVE";

export const PAIRWISE_COMBINATIONS_TYPES = {
  BINARY_CHOICE: "BINARY_CHOICE",
  WEIGHT_BASED_CHOICE: "WEIGHT_BASED_CHOICE",
};
