/* eslint-disable import/no-anonymous-default-export */

export default {
  ONLY_QUESTION_INFO: "ONLY_QUESTION_INFO",
  PAIRWISE_COMBINATIONS: "PAIRWISE_COMBINATIONS",
  SHORT_ANSWER: "SHORT_ANSWER",
  MULTIPLE_CHOICE: "MULTIPLE_CHOICE",
  IMAGE_PAIRWISE_COMBINATIONS: "IMAGE_PAIRWISE_COMBINATIONS",
  CITIZEN_PROFILE: "CITIZEN_PROFILE",
  TERRITORIAL_COVERAGE: "TERRITORIAL_COVERAGE",
  GEOLOCATION: "GEOLOCATION",
  EMBEDDED_QUESTION: "EMBEDDED_QUESTION",
};
