export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const AUTHENTICATE_USER_PENDING = "AUTHENTICATE_USER_PENDING";
export const AUTHENTICATE_USER_FAILED = "AUTHENTICATE_USER_FAILED";
export const LOGOUT_USER = "LOGOUT_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
