export const GET_USER_PROFILES = "GET_USER_PROFILES";
export const SET_USER_PROFILES = "SET_USER_PROFILES";
export const CREATE_USER_PROFILE = "CREATE_USER_PROFILE";
export const CREATE_USER_PROFILE_FULFILLED = "CREATE_USER_PROFILE_FULFILLED";

export const GET_USER_PROFILE_QUESTION_INFO = "GET_USER_PROFILE_QUESTION_INFO";
export const SET_USER_PROFILE_QUESTION_INFO = "SET_USER_PROFILE_QUESTION_INFO";

export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
