export const SET_APP_CONFIGURATIONS = "SET_APP_CONFIGURATIONS";

export const SET_APP_TRANSLATIONS = "SET_APP_TRANSLATIONS";
export const SET_CURRENT_TRANSLATION = "SET_CURRENT_TRANSLATION";
export const SET_APP_LOADED = "SET_APP_LOADED";
